spring:
  application:
    name: finance

  # -------------------------------
  # PostgreSQL + HikariCP
  # -------------------------------
  datasource:
    url: jdbc:postgresql://localhost:5432/finance_management
    username: finance_user
    password: ${DB_PASSWORD:secure_password_123}  # Use env var in prod
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 60000

  # -------------------------------
  # JPA / Hibernate
  # -------------------------------
  jpa:
    hibernate:
      ddl-auto: validate        # Flyway manages schema → validate only
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: false
        jdbc:
          lob:
            non_contextual_creation: true
        hbm2ddl:
          auto: validate

  # -------------------------------
  # Flyway (Schema + Data Migration)
  # -------------------------------
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
    clean-disabled: true      # Safety in production
    out-of-order: false

  # -------------------------------
  # SQL Init (Optional: data.sql)
  # -------------------------------
  sql:
    init:
      mode: always
      platform: postgresql
      data-locations: classpath:data.sql
  
  jwt:
    secret: ${JWT_SECRET:superlongrandombase64string1234567890abcdefghijklmnopqrstuvwxyz}
    expiration: 86400000